[licenses]
allow = [
  # permissive licenses
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
  # permissive license with unclear patent grant
  "CC0-1.0",
  # weak/limited copyleft licenses
  "MPL-2.0",
]

# Clearify licence: https://github.com/briansmith/ring/issues/902
# Plan to remove OpenSSL: https://github.com/briansmith/ring/issues/1827
[[licenses.clarify]]
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name = "ring"

[advisories]
ignore = [
  # Temporary accept those until all crates are updated
  "RUSTSEC-2024-0436",
  "RUSTSEC-2025-0022",
  "RUSTSEC-2025-0024",
]
yanked = "warn"

[bans]
multiple-versions = "allow"

[sources]
allow-git = ["https://github.com/alloy-rs/evm", "https://github.com/paradigmxyz/reth"]
