// This file is auto-generated by build.rs
// DO NOT EDIT MANUALLY
// To change the key, set the KEY_ENCRYPTION_PWD environment variable (32 hex chars)

pub const KEY_ENCRYPTION_PWD: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
